shared:
  target: test
  outputs:
    test:
      type: bigquery
      method: oauth
      project: "{{ env_var('PRJ_NAME') }}"
      dataset: test_dbt
      threads: 4
      timeout_seconds: 120
      job_retries: 1
      location: US
      priority: interactive

    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('PRJ_NAME') }}"
      dataset: test_dbt
      threads: 2
      timeout_seconds: 240
      job_retries: 1
      location: US
      priority: interactive
      
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('PRJ_NAME') }}"
      dataset: shared
      threads: 4
      timeout_seconds: 120
      job_retries: 1
      location: US
      priority: interactive

    sbx:
      type: bigquery
      method: oauth
      project: "{{ env_var('PRJ_NAME') }}"
      dataset: shared
      threads: 1
      timeout_seconds: 240
      job_retries: 1
      location: US
      priority: interactive
